server:
  port: 8762
spring:
  application:
    name: service-system
  zipkin:
    base-url: http://zipkin-server:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
feign:
  hystrix:
    enabled: true